import type { Metadata } from "next";
import { Roboto, Prosto_One} from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ['300','200'],
  variable: "--font-roboto",
  subsets: ["latin","cyrillic"],
});

const prostoOne = Prosto_One({
  weight: '400',
  variable: "--font-prosto-one",
  subsets: ["latin","cyrillic"],
});

export const metadata: Metadata = {
  title: "ttc es",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${prostoOne.variable}`}>
        {children}
      </body>
    </html>
  );
}
